function Import-WEPSXeroxConfig {
    <#
    .SYNOPSIS
        Imports Xerox-specific printer configuration from a JSON file.

    .DESCRIPTION
        Imports a set of registry values from a JSON file generated by
        Export-WEPSXeroxConfig and applies them to one or more printers.

        The function writes values into the printer configuration registry hive:
            HKLM\SYSTEM\CurrentControlSet\Control\Print\Printers\<PrinterName>

        During execution:
        - Target printers are validated
        - The Print Spooler service is stopped to allow safe registry writes
        - Registry values are applied from the JSON file
        - Optional spooler restart is performed

        Special handling is applied to the "Default DevMode" value:
        - The embedded printer name is updated to match the target printer

        Binary values:
        - Base64-encoded values are restored
        - '<BINARY_DATA_REDACTED>' entries are skipped

        This function is designed specifically for Xerox Global Print Driver (PCL6)
        registry structures and should not be used for other printer vendors
        without validation.

    .PARAMETER PrinterName
        One or more printer names to which the configuration will be applied.

    .PARAMETER FilePath
        Path to a JSON file previously created using Export-WEPSXeroxConfig.

    .PARAMETER RestartSpooler
        If specified, the Print Spooler service is started after import completes.

    .PARAMETER RequireXeroxGPD
        Ensures only printers using the Xerox Global Print Driver PCL6 are modified.
        Printers using other drivers will be skipped.

    .OUTPUTS
        System.Management.Automation.PSCustomObject

        Returns one object per printer with the following fields:
            Printer - Printer name
            Success - Boolean indicating success or failure
            Errors  - Array of error messages (if any)

    .NOTES
        This function performs direct registry modification and stops the Print Spooler.
        It should be used with caution in production environments.

        Recommended usage:
            - Validate JSON content before import
            - Test on a single printer first
            - Use -WhatIf for dry-run validation (where applicable)

        This function does NOT provide rollback capability.

        Designed for Xerox GPD environments (tested on 5591.900.0.0). Behavior
        with other drivers is not guaranteed.

    .EXAMPLE
        Import-WEPSXeroxConfig -PrinterName "PRN-01" -FilePath "C:\Temp\PrinterConfig.json" -RestartSpooler -Verbose

        Imports the configuration into PRN-01 and restarts the spooler afterward.

    .EXAMPLE
        Import-WEPSXeroxConfig -PrinterName "PRN-01","PRN-02" -FilePath "C:\Temp\Config.json" -RestartSpooler

        Applies the same configuration file to multiple printers.
        Each printer is processed independently and results are returned per printer.

    .EXAMPLE
        Import-WEPSXeroxConfig -PrinterName "PRN-01" -FilePath "C:\Temp\Config.json" -RequireXeroxGPD

        Imports configuration only if PRN-01 is using the Xerox Global Print Driver PCL6.
        Otherwise, the printer is skipped.

    .EXAMPLE
        $results = Import-WEPSXeroxConfig -PrinterName "PRN-01","PRN-02" -FilePath "C:\Temp\Config.json"

        $results | Where-Object { -not $_.Success }

        Runs the import and filters for printers that failed.
    .EXAMPLE
        Import-WEPSXeroxConfig -PrinterName PRN-01,PRN-02 -FilePath C:\Temp\Xerox_with_Stapling_with_Horizontal.json -Verbose
        VERBOSE: Performing the operation "Stop" on target "Spooler". 
        VERBOSE: Performing the operation "Set 'xColor'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-01\PrinterDriverData".
        VERBOSE: Performing the operation "Set 'xUPDCurrentModel'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-01\PrinterDriverData".
        VERBOSE: Performing the operation "Set 'xCurrentProdUID'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-01\PrinterDriverData".
        VERBOSE: Performing the operation "Set 'XrxDeviceSettings'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-01\PrinterDriverData".
        VERBOSE: Performing the operation "Set 'NamedSettingsSupported'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-01\PrinterDriverData".
        VERBOSE: Performing the operation "Set 'TrayFormTable'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-01\PrinterDriverData".
        VERBOSE: Performing the operation "Set 'TrayFormMapSize'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-01\PrinterDriverData".
        VERBOSE: Performing the operation "Set 'TrayFormMap'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-01\PrinterDriverData".
        VERBOSE: Performing the operation "Set 'TrayFormKeywordSize'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-01\PrinterDriverData".
        VERBOSE: Performing the operation "Set 'TrayFormKeyword'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-01\PrinterDriverData".
        VERBOSE: Performing the operation "Set 'FontCart'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-01\PrinterDriverData".
        VERBOSE: Performing the operation "Set 'AdminDevDefaults'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-01\PrinterDriverData".
        VERBOSE: Performing the operation "Set 'AdminDocDefaults'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-01\PrinterDriverData".
        VERBOSE: Performing the operation "Set 'printBinNames'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-01\DSDriver".
        VERBOSE: Performing the operation "Set 'printColor'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-01\DSDriver".
        VERBOSE: Performing the operation "Set 'printMediaSupported'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-01\DSDriver".
        VERBOSE: Performing the operation "Set 'printMaxXExtent'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-01\DSDriver".
        VERBOSE: Performing the operation "Set 'printMaxYExtent'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-01\DSDriver".
        VERBOSE: Performing the operation "Set 'printMinXExtent'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-01\DSDriver".
        VERBOSE: Performing the operation "Set 'printMinYExtent'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-01\DSDriver".
        VERBOSE: Performing the operation "Set 'printRate'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-01\DSDriver".
        VERBOSE: Performing the operation "Set 'printPagesPerMinute'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-01\DSDriver".
        VERBOSE: Performing the operation "Set 'Default DevMode'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-01".
        VERBOSE: Import complete for 'PRN-01' 
        VERBOSE: Performing the operation "Set 'xColor'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-02\PrinterDriverData".
        VERBOSE: Performing the operation "Set 'xUPDCurrentModel'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-02\PrinterDriverData".
        VERBOSE: Performing the operation "Set 'xCurrentProdUID'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-02\PrinterDriverData".
        VERBOSE: Performing the operation "Set 'XrxDeviceSettings'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-02\PrinterDriverData".
        VERBOSE: Performing the operation "Set 'NamedSettingsSupported'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-02\PrinterDriverData".
        VERBOSE: Performing the operation "Set 'TrayFormTable'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-02\PrinterDriverData".
        VERBOSE: Performing the operation "Set 'TrayFormMapSize'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-02\PrinterDriverData".
        VERBOSE: Performing the operation "Set 'TrayFormMap'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-02\PrinterDriverData".
        VERBOSE: Performing the operation "Set 'TrayFormKeywordSize'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-02\PrinterDriverData".
        VERBOSE: Performing the operation "Set 'TrayFormKeyword'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-02\PrinterDriverData".
        VERBOSE: Performing the operation "Set 'FontCart'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-02\PrinterDriverData".
        VERBOSE: Performing the operation "Set 'AdminDevDefaults'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-02\PrinterDriverData".
        VERBOSE: Performing the operation "Set 'AdminDocDefaults'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-02\PrinterDriverData".
        VERBOSE: Performing the operation "Set 'printBinNames'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-02\DSDriver".
        VERBOSE: Performing the operation "Set 'printColor'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-02\DSDriver".
        VERBOSE: Performing the operation "Set 'printMediaSupported'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-02\DSDriver".
        VERBOSE: Performing the operation "Set 'printMaxXExtent'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-02\DSDriver".
        VERBOSE: Performing the operation "Set 'printMaxYExtent'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-02\DSDriver".
        VERBOSE: Performing the operation "Set 'printMinXExtent'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-02\DSDriver".
        VERBOSE: Performing the operation "Set 'printMinYExtent'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-02\DSDriver".
        VERBOSE: Performing the operation "Set 'printRate'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-02\DSDriver".
        VERBOSE: Performing the operation "Set 'printPagesPerMinute'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-02\DSDriver".
        VERBOSE: Performing the operation "Set 'Default DevMode'" on target "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\PRN-02".
        VERBOSE: Import complete for 'PRN-02'
        VERBOSE: Import process completed.

        Printer  Success Errors
        -------  ------- ------
        PRN-01    	True
        PRN-02   	True
    #>

    [CmdletBinding(SupportsShouldProcess = $true)]
    param(
        [Parameter(Mandatory)]
        [string[]]$PrinterName,

        [Parameter(Mandatory)]
        [string]$FilePath,

        [Parameter()]
        [switch]$RestartSpooler,

        [Parameter()]
        [switch]$RequireXeroxGPD
    )

    begin {
        function Set-DevModeDeviceName {
            param(
                [Parameter(Mandatory)]
                [byte[]]$DevModeBytes,

                [Parameter(Mandatory)]
                [string]$NewPrinterName
            )

            if ($DevModeBytes.Length -lt 64) {
                throw "Default DevMode data is too small."
            }

            $name = $NewPrinterName.Substring(0, [Math]::Min(31, $NewPrinterName.Length))
            $nameBytes = [System.Text.Encoding]::Unicode.GetBytes($name)

            $buf = New-Object byte[] 64
            [array]::Copy($nameBytes, $buf, [Math]::Min($nameBytes.Length, 62))

            [array]::Copy($buf, 0, $DevModeBytes, 0, 64)
            return $DevModeBytes
        }

        function ConvertTo-ValueKind {
            param([Parameter(Mandatory)]$Kind)

            if ($Kind -is [string]) {
                return [Microsoft.Win32.RegistryValueKind]::$Kind
            }
            else {
                return [Microsoft.Win32.RegistryValueKind]([int]$Kind)
            }
        }

        if (-not (Test-Path -LiteralPath $FilePath)) {
            throw "File not found: $FilePath"
        }

        $items = Get-Content -LiteralPath $FilePath -Raw | ConvertFrom-Json
        if ($items -isnot [System.Array]) { $items = @($items) }

    }

    process {
        $validatedPrinters = foreach ($printer in $PrinterName) {
            try {
                $p = Get-Printer -Name $printer -ErrorAction Stop

                if ($RequireXeroxGPD -and ($p.DriverName -ne 'Xerox Global Print Driver PCL6')) {
                    Write-Warning "Skipping '$printer' due to driver mismatch."
                    continue
                }
                $p.Name
            }
            catch {
                Write-Warning "Skipping '$printer' (not found)."
            }
        }
    }

    end {

        if ($validatedPrinters.Count -eq 0) {
            Write-Warning "No valid printers found."
            return
        }

        $results = @()
        $spoolerStopped = $false

        if ($PSCmdlet.ShouldProcess("Spooler", "Stop")) {
            Stop-Service -Name Spooler -Force -ErrorAction Stop
            $spoolerStopped = $true
        }

        $results = foreach ($printer in $validatedPrinters) {
            $errors = [System.Collections.Generic.List[string]]::new()
            $success = $true

            try {
                $baseKey = "registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\$printer"

                foreach ($item in $items) {

                    if (-not $item.Name -or -not $item.Kind) {
                        continue
                    }

                    $targetKey = if ([string]::IsNullOrWhiteSpace($item.SubKey)) {
                        $baseKey
                    }
                    else {
                        [System.IO.Path]::Combine($baseKey, $item.SubKey)
                    }

                    if (-not (Test-Path -LiteralPath $targetKey)) {
                        continue
                    }

                    $kind = ConvertTo-ValueKind $item.Kind
                    $data = $item.Data

                    if ($kind -eq [Microsoft.Win32.RegistryValueKind]::Binary) {
                        if ($data -eq '<BINARY_DATA_REDACTED>') { continue }

                        $valueToWrite = [Convert]::FromBase64String([string]$data)

                        if ($item.Name -eq 'Default DevMode') {
                            $valueToWrite = Set-DevModeDeviceName $valueToWrite $printer
                        }
                    }
                    elseif ($kind -eq [Microsoft.Win32.RegistryValueKind]::MultiString) {
                        $valueToWrite = [string[]]$data
                    }
                    elseif ($kind -eq [Microsoft.Win32.RegistryValueKind]::DWord) {
                        $valueToWrite = [int]$data
                    }
                    else {
                        $valueToWrite = [string]$data
                    }

                    if ($PSCmdlet.ShouldProcess($targetKey, "Set '$($item.Name)'")) {
                        Set-ItemProperty -LiteralPath $targetKey -Name $item.Name -Value $valueToWrite -Type $kind
                    }
                }

                Write-Verbose "Import complete for '$printer'"
            }
            catch {
                $success = $false
                $null = $errors.Add($_.Exception.Message)
                Write-Warning "Import failed for '$printer': $($_.Exception.Message)"
            }

            [PSCustomObject]@{
                Printer = $printer
                Success = $success
                Errors  = $errors -join '; '
            }
        }

        if ($RestartSpooler -and $spoolerStopped -and $PSCmdlet.ShouldProcess("Spooler", "Start")) {
            Start-Service -Name Spooler
        }

        Write-Verbose "Import process completed."

        return $results
    }
}
